#!/bin/bash

cat << EOF > /etc/mysql/init.sql
CREATE DATABASE IF NOT EXISTS \`${MARIADB_DATABASE}\`;
CREATE USER IF NOT EXISTS '${MARIADB_USER}'@'%' IDENTIFIED BY '${MARIADB_PASSWORD}';
GRANT ALL PRIVILEGES ON \`${MARIADB_DATABASE}\`.* TO '${MARIADB_USER}'@'%';
ALTER USER 'root'@'localhost' IDENTIFIED BY '${MARIADB_ROOT_PASSWORD}';
FLUSH PRIVILEGES;

USE \`${MARIADB_DATABASE}\`;

CREATE TABLE IF NOT EXISTS users (
	id INT AUTO_INCREMENT PRIMARY KEY,
	email VARCHAR(255) NOT NULL,
	password VARCHAR(255) NOT NULL,
	pseudo VARCHAR(255) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	reset_token VARCHAR(255),
	reset_token_expiry DATETIME
);

CREATE TABLE IF NOT EXISTS images (
	id INT AUTO_INCREMENT PRIMARY KEY,
	user_id INT NOT NULL,
	filename VARCHAR(255) NOT NULL,
	filepath VARCHAR(255) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

	FOREIGN KEY (user_id)
		REFERENCES users(id)
		ON DELETE CASCADE
);

EOF

mysql_install_db
mysqld

# ALTER TABLE users ADD COLUMN reset_token VARCHAR(255);

