services:
  nginx:
    build: nginx/.
    container_name: nginx
    restart: always
    env_file: .env
    depends_on:
      - php
      - mariadb
    ports:
      - "8443:443"
    volumes:
      - php_data:/var/www/html
      - images:/var/www/html/public/images
    networks:
      camagraou:

  php:
    build: php/.
    expose:
      - "9000"
    container_name: php
    restart: always
    env_file: .env
    depends_on:
      - mariadb
      - mailhog
    volumes:
      - php_data:/var/www/html
      - images:/var/www/html/public/images
    networks:
      camagraou:

  mariadb:
    build: mariadb/.
    container_name: mariadb
    restart: always
    env_file: .env
    volumes:
      - database:/var/lib/mysql
    networks:
      camagraou:

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    restart: always
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      camagraou:

networks:
  camagraou:
    driver : bridge

volumes:
  php_data:
    driver: local
    driver_opts:
      type: none
      device: ../camagru
      o: bind

  database:

  images:
