services:
  nginx:
    build: nginx/.
    container_name: nginx
    restart: always
    env_file: .env
    depends_on:
      - php
      - mariadb
    ports:
      - "8443:443"
    volumes:
      - php_data:/var/www/html
    networks:
      inception:

  php:
    build: php/.
    expose:
      - "9000"
    container_name: php
    restart: always
    env_file: .env
    depends_on:
      - mariadb
    volumes:
      - php_data:/var/www/html
    networks:
      inception:

  mariadb:
    build: mariadb/.
    container_name: mariadb
    restart: always
    env_file: .env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      inception:

networks:
  inception:
    driver : bridge

volumes:
  php_data:
    driver: local
    driver_opts:
      type: none
      device: ../src
      o: bind

  db_data:
    driver: local
    driver_opts:
      type: none
      device: ../db
      o: bind
